baseURL = 'https://alexandrepoupeau.com/personal/'
canonifyURLs = true
relativeURLs = false
languageCode = 'en-us'
title = 'Alexandre Poupeau - Website'
defaultContentLanguage = 'en'
publishDir = 'docs'
staticDir = 'static'

[params]
author = "Alexandre Poupeau"
email = "alexandre.poupeau.contact@gmail.com"
siteName = 'A. Poupeau'
city = 'Lyon'
country = 'FRANCE'
[params.music]
  artistName = "Chill Wind"
  artistImgPath = "/img/music/compo/cw-square-white.png"
[params.navigation]
  help = 'Help'

[languages]
  [languages.en]
    title = 'A. Poupeau Website'
    contentDir = "content/en"
    languageName = "English"
    weight = 1
    copyright = 'All rights reserved.'
    [languages.en.params]
      languageShort = "EN"
      linkedin = 'https://linkedin.com/whoever'
  [languages.fr]
    title = 'A. Poupeau Site Web'
    contentDir = "content/fr"
    languageName = "Français"
    weight = 2
    copyright = 'Tous droits réservés.'
    [languages.fr.params]
      languageShort = "FR"
      linkedin = 'https://linkedin.com/fr/whoever'
      [languages.fr.params.navigation]
        help = 'Aide'
  [languages.es]
    title = 'A. Poupeau Sitio Web'
    contentDir = "content/es"
    languageName = "Español"
    weight = 3
    copyright = 'Todos los derechos reservados.'
    [languages.es.params]
      languageShort = "ES"

disableKinds = ["taxonomy"]
